### PR TITLE
Update ephemeral-roles.go

### PR DESCRIPTION
**Pull request by Aareon**
I hope this helps in some way. My main goal was to remove as much duplicate code as possible without breaking the thing. I also wanted to try to remove at least one unnecessary function call if need be. Please request any changes as need be, I’m quite new to Golang. Thanks for the awesome bot!

### CODE REVIEW

**Comment by ewohltman** [comment]
Thanks very much for the PR! I'll take a closer look and get back to you with any feedback ASAP!

**Comment by ewohltman** [comment]
Thanks very much for the PR! I'll take a closer look and get back to you with any feedback ASAP!

**Comment by ewohltman** [comment]
Thanks very much for the PR! I'll take a closer look and get back to you with any feedback ASAP!

**Comment by Aareon** [comment]
I’m not sure if that error is my doing, or if it’s the nature of the script, but if there is something that needs changing, I will gladly do so.

**Comment by ewohltman** [comment]
Looks good to me, great catch/idea with replacing the environment variable lookups with a slice of strings!

If I could request one last minor update: if we're going to move from explicitly closing the `dgBotSession` to deferring it, could we move the defer to right after the Open() error check? 

```
	// Open the websocket and begin listening
	err = dgBotSession.Open()
	if err != nil {
		log.WithError(err).Fatalf("Error opening Discord session")
	}
	defer dgBotSession.Close()
```

I'd be happy to merge right in with that, thanks!

**Comment by Aareon** [comment]
Absolutely! I’d be happy to polish this off tomorrow, I’m a bit sick today. If you have any other requests for changes, please let me know. I’m kind of learning as I Go 😉

**Comment by Aareon** [comment]
I’m concerned now about how you feel about my usage of the switch-case in this scenario. It may be a bit of a “pedantic” change. My reasoning behind using it was almost exactly that. I did figure that instead of doing `len(dgBotSession.State.Guilds` as many times as it’s done now, it may be better to store it and reuse it.

On another note, it does add a smidge more garbage. So that is something to consider.

**Comment by ewohltman** [comment]
Since it's only an extra `int`, I'm not concerned about the extra "garbage" from a new, meaningful variable 😄 

If I am not mistaken, because it is a primitive data type (allocated onto stack instead of heap?) scoped within the `for` loop, each time the loop block completes the memory allocated for the `int` is freed because it is no longer in scope so there would be no garbage to collect (and maybe the same block in memory is re-allocated on the next iteration, or we get it from somewhere else).

Otherwise, merging! 🎉

**Pull request merged**
